budgettracker/urls.py
from django.urls import path
from budgettracker.views import BudgettrackerCreate, BudgettrackerUpdate, BudgettrackerDelete
from . import views

urlpatterns = [
    path('', views.index, name='budgettracker-index'),
    path('add', BudgettrackerCreate.as_view(), name='budgetracker-add'),
    path('<int:pk>/update', BudgettrackerUpdate.as_view(), name='budgettracker-update'),
    path('<int:pk>/delete', BudgettrackerDelete.as_view(), name='budgettracker-delete'),
    path ('test',views.test, name='test'),
    path ('ajax/get_budget_average', views.get_budget_average, name='get-budget-average'),
    path ('ajax/check_max_date', views.check_max_date, name='check_max_date'),
    path ('budget-list', views.budget_list, name='budget-list'),

]

mybudget/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('categories/', include('categories.urls')),    
    path('users/', include('users.urls')), 
    path('accounts/', include('accounts.urls')),
    path('accounthistory/', include('accounthistory.urls')),
    path ('transfers/', include('transfers.urls')),
    path ('transactions/', include('transactions.urls')),
    path ('budgettracker/', include('budgettracker.urls'))
]

users/urls.py
from django.urls import path
from . import views
from users.views import RegisterView, LoginView, PasswordResetView, PasswordChangeView, PasswordChangeDoneView, PasswordResetDoneView, PasswordResetCompleteView, PasswordResetConfirmView
from django.contrib.auth import views as auth_views
urlpatterns = [

    path('register/', RegisterView.as_view(), name='register'),
    path ('login/',LoginView.as_view(), name='login'),
    path ('logout/',auth_views.LogoutView.as_view(), name='logout'),
    path ('password-reset/',PasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('password-change/', PasswordChangeView.as_view(), name='password_change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(), name='password_change_done'),
 

]

budgettracker/models.py
from django.db import models
from django.contrib.auth.models import User
from categories.models import Category
class BudgetTracker(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    date = models.DateField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    budget_amount = models.FloatField()
    monthly_spend = models.FloatField(default=0)
    class Meta:
        ordering = ["category"]
    def __str__(self):
        return '%s  %s  %s %s %s ' %(self.date, self.category, self.budget_amount, self.id, self.monthly_spend)
    

    def get_absolute_url(self):
        return reverse('budgettracker-index', args=[self.id])

class BudgetLeft (models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    amount = models.FloatField()
    def __str__(self):
        return '%s  %s ' %(self.amount, self.user)

transactions/models.py
from django.db import models
from django.forms import ModelForm
from categories.models import Category
from accounts.models import Account
from django.contrib.auth.models import User
class Transaction(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default = 1) 
    store = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    amount = models.FloatField()
    trans_date = models.DateField(verbose_name= ('Transaction Date'))
   #add a category as a foreign key later that pulls this in as a dropdown
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    account_name = models.ForeignKey(Account, on_delete=models.CASCADE)


    def get_absolute_url(self):
        return reverse('transactions-index', args=[self.id])
    
    def __str__(self):
        return '%s  %s  %s %s %s %s' %(self.store, self.description, self.amount, self.trans_date, self.category, self.account_name)

budgettracker/forms.py
from bootstrap_datepicker_plus import DatePickerInput, MonthPickerInput
from django import forms
import datetime
from .models import BudgetTracker
from categories.models import Category
from django.contrib.auth.models import User
from django.utils.safestring import mark_safe
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Column
class GetDateForm(forms.Form):
    start_month = forms.DateField(
        widget=
        MonthPickerInput(format='%Y-%m'), initial=datetime.date.today(), input_formats=["%Y-%m"])
    
# validation datefield

class CreateBudget(forms.ModelForm):
    class Meta:
        model = BudgetTracker
        exclude =('user','monthly_spend')
        #fields='__all__'
        widgets = {
            'date': MonthPickerInput().start_of('2020-10-01'), # default date-format %m/%d/%Y will be used
        }
  
    def __init__(self, *args, logged_user_id=None, **kwargs):
       self.user = kwargs.pop('user')
       super().__init__(*args, **kwargs)

       if logged_user_id is not None:
           print (logged_user_id)
           self.fields['category'].queryset = Category.objects.filter(
               user=logged_user_id
           )

    def clean (self):
         user = self.user
         cleaned_data = super().clean()
         date = cleaned_data['date']
         category = cleaned_data['category']
         budget_amount = cleaned_data['budget_amount']
         check = BudgetTracker.objects.filter( user=self.user, date=date, category__category = category)

         if BudgetTracker.objects.filter(user=self.user, date=date, category__category = category).exists():
            raise forms.ValidationError(
    ((mark_safe('<div class="alert alert-danger text-center" role="alert">A budget already exist for'+ str(category)+'for '+ str(date.month) +'-'+ str(date.day)+ '. <a href="/budgettracker/'+str(check[0].id)+'/update">Update budget?</a></div>')))
 )

class UpdateBudget(forms.ModelForm):
    class Meta:
        model = BudgetTracker
        exclude =('user','monthly_spend')
        #fields='__all__'
        widgets = {
            'date': MonthPickerInput(), # default date-format %m/%d/%Y will be used
        }
  
    def __init__(self, *args, **kwargs):
       self.user = kwargs.pop('user')
       super().__init__(*args, **kwargs)


    def clean (self):
         user = self.user
         cleaned_data = super().clean()
         date = cleaned_data['date']
         category = cleaned_data['category']
         budget_amount = cleaned_data['budget_amount']

budgettracker/views.py
from django.http import HttpResponse, JsonResponse
from django.template import loader
from django.db.models import Sum, Max, Avg, F, Exists,Q
from .models import BudgetTracker
from transactions.models import Transaction
from accounts.models import Account
from transfers.models import Transfer
from categories.models import Category
from .forms import GetDateForm
from django.shortcuts import render
from datetime import datetime, timedelta, date
import calendar
from calendar import monthrange
from .forms import CreateBudget, UpdateBudget
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic import ListView
from django.urls import reverse_lazy
from dateutil.relativedelta import relativedelta
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from mybudget.common import *
#from django_datatables_view.base_datatable_view import BaseDatatableView
from django.utils.html import escape

from django_tables2 import SingleTableView
from .tables import BudgetTable

@login_required

def get_cat_budget(request):
    category = request.GET.get('category')
    thedate = request.GET.get('thedate')
 
    #today = datetime.today()
    #print (today)
    thedate = datetime.strptime(thedate, '%m/%d/%Y')
    first = thedate.replace(day=1)
    last_day_last_month = first - timedelta(days=1)
    first_day_last_month = last_day_last_month.replace(day=1)

    start_date = (first_day_last_month.year, first_day_last_month.month, first_day_last_month.day)
    start_date= str(start_date[0]) +"-"+ str(start_date[1]) +"-"+ str(start_date[2])

    end_date = (last_day_last_month.year, last_day_last_month.month, last_day_last_month.day)
    end_date = str(end_date[0]) +"-"+ str(end_date[1]) +"-"+ str(end_date[2])
    #work on this tomorrow
    #get last month's budget and subtract any transactions that happend on that budget to show what's left
    previous_budget = BudgetTracker.objects.filter(id=category, date__range=[start_date, end_date]).values('budget_amount')
    previous_budget = previous_budget[0]  
    print (previous_budget)
    return JsonResponse({'data':previous_budget})

def get_topfivespend(start_month, end_month, request):
    top_spend = BudgetTracker.objects.filter(user=request.user, date__range=[start_month,end_month]).order_by('monthly_spend')[:5]
    return top_spend

def get_monthly_budget (start_month, request):
    template = loader.get_template ('budgettracker/index.html')
    #do all the date stuff

    today = str(date.today())

    num_days = monthrange(start_month.year, start_month.month)
    exclude_list = ['Initial Balance', 'Income']             
    enddate = (start_month.year, start_month.month, num_days[1])
    end_year = str(enddate[0])
    end_month = str(enddate[1])
    end_day = str(enddate[2])
    enddate = end_year+"-"+ end_month+ "-" + end_day        
    first_day = (start_month.year, start_month.month, 1)
    start_year = str(first_day[0])
    start_mnth = str(first_day[1])
    start_day = str(first_day[2])
    startdate = start_year+"-"+ start_mnth+ "-" + start_day
    budget_month = startdate
    budget_month_human = start_month.strftime("%B %Y")

    first_of_month = get_first_of_month(start_month)
    last_of_month = get_last_of_month(start_month)
    first_of_last_month = get_first_of_last_month(start_month)
    last_of_last_month = get_last_of_last_month(start_month)
    first_of_next_month = get_first_of_next_month(start_month)
    last_of_next_month = get_last_of_next_month(start_month)
    #get the records from this month and the last month
    b_f_month = BudgetTracker.objects.filter(date__range=[startdate,enddate], user=request.user).exclude(category__category=exclude_list)
    b_f_last_month = BudgetTracker.objects.filter(date__range=[first_of_last_month,last_of_last_month], user=request.user).exclude(category__category=exclude_list)

    #b_f_next_month = BudgetTracker.objects.filter(date__range=[first_of_next_month,last_of_next_month], user=request.user).exclude(category__category=exclude_list)
    #print ('----budget for next month----')
    #print (b_f_next_month)
    #if not b_f_next_month:
    #    print ('empty query set yo!')
    #calculate in the total money left and percentage left to show in table
    budgets_for_selected_month = b_f_month.annotate(total_left=(F('budget_amount')+F('monthly_spend')), carryover = (F('category__carry_over')), total_percent_left = ((F('monthly_spend')+F('budget_amount'))/F('budget_amount'))*100).order_by('-budget_amount')
    
    budget_list = []
    for budget in budgets_for_selected_month:
        last_month_spend = 0
        for bud in b_f_last_month:

                if budget.category == bud.category:
                    last_month_spend = bud.monthly_spend
                else:
                    last_month_spend = 0    
        budget_list.append([budget.category, budget.budget_amount, budget.monthly_spend, budget.total_left, budget.carryover, budget.total_percent_left, last_month_spend, budget.id])
        last_month_spend = 0
 
    #total budgeted this month
    budget_total =  BudgetTracker.objects.filter(date__range=[startdate,enddate], user=request.user).aggregate(sum=Sum('budget_amount'))['sum'] or 0.00
    #total spend this month
    total_spend =  BudgetTracker.objects.filter(date__range=[startdate,enddate], user=request.user).aggregate(sum=Sum('monthly_spend'))['sum'] or 0.00
    #get savings and investment categories - don't include in spend calculation
    sav_inv_categories = Category.objects.filter(savings_or_investment=True, user=request.user)
    print (sav_inv_categories)
    savings_amount = 0
    total_savings_amount = 0
    for category in sav_inv_categories:
        savings_amount = BudgetTracker.objects.filter(user=request.user, date__range=[first_of_month, last_of_month]).filter(category__category = category).aggregate(sum=Sum('budget_amount'))['sum'] or 0.00 
        total_savings_amount = total_savings_amount + savings_amount

    if total_spend < 0:
        total_spend_percentage = (total_spend/(budget_total-total_savings_amount))*-100
    else:
        total_spend_percentage = 0
        

    #money left to budget
    all_transactions_to_this_month = Transaction.objects.filter(user=request.user, trans_date__lte=last_of_last_month).aggregate(sum=Sum('amount'))['sum'] or 0.00
    transaction_income_this_month = Transaction.objects.filter(category__category = 'Income', user=request.user, trans_date__range=[first_of_month, last_of_month]).aggregate(sum=Sum('amount'))['sum'] or 0.00 
    transaction_initial_balance_this_month = Transaction.objects.filter( category__category = 'Initial Balance', user=request.user, trans_date__range=[first_of_month,last_of_month]).aggregate(sum=Sum('amount'))['sum'] or 0.00
    transactions_savings_investments = Transaction.objects.filter(category__savings_or_investment=True, user=request.user, trans_date__range=[first_of_month, last_of_month]).aggregate(sum=Sum('amount'))['sum'] or 0.00
   
    budget_this_month = BudgetTracker.objects.filter(user=request.user, date__range=[first_of_month, last_of_month]).exclude(category__category = exclude_list).aggregate(sum=Sum('budget_amount'))['sum'] or 0.00    
    left_to_budget = all_transactions_to_this_month - budget_this_month + transaction_income_this_month +  transaction_initial_balance_this_month

    #total money left to spend
    money_left_to_spend = budget_total + total_spend - total_savings_amount - transactions_savings_investments
    #current savings
    current_savings = total_savings_amount + transactions_savings_investments

        
    form = GetDateForm()   
    form.fields['start_month'].label = "View budget For:"

    context= {
    'form': form, 
    'budgets_for_selected_month': budgets_for_selected_month,
    'budget_list' : budget_list,
    'budget_total' : budget_total,
    'total_budget_left' : left_to_budget,
    'total_spend' : total_spend,
    'total_monthly_budget_percentage' : total_spend_percentage,
    'total_monthly_budget_left' : money_left_to_spend,
    'current_savings' : current_savings,
    'budget_month_date' : budget_month,
    'budget_month_human' : budget_month_human,
    }
    return (context)

@login_required
def index(request):
 template = loader.get_template ('budgettracker/index.html')
 personal_budget_array =[]
 today = str(date.today())
 record_count= BudgetTracker.objects.filter(user=request.user).count()
 if record_count > 0 :   
    if request.method == 'POST':
        form = GetDateForm(request.POST)
        if form.is_valid():
             print ('--------If form is valid pass in june-------')
             form.fields['start_month'].label = "View budget for:"        

            #get the start and end date to pull all budget items from the model
             start_month = form.cleaned_data['start_month']
             print (start_month)
             end_month = get_last_of_month(start_month)
             context = get_monthly_budget (start_month, request)
             top_five = get_topfivespend(start_month, end_month, request)
             context.update({'top_five' : top_five})
            # return HttpResponse((template.render(context,request)))
             return render(request, 'budgettracker/index.html',context)
    else:
        print ('inside else of post------------')
        today = datetime.today()
        start_month = get_first_of_month (today)
        end_month = get_last_of_month (today)
        top_five = get_topfivespend(start_month, end_month, request)       
        context = get_monthly_budget (today, request)
        context.update({'top_five' : top_five})
    return render(request, 'budgettracker/index.html',context)
 else:
     context={}
     return render (request, 'budgettracker/index.html', context)

class BudgettrackerCreate (LoginRequiredMixin, CreateView):

     template_name = 'budgettracker/budgettracker_form.html'
     form_class = CreateBudget

templates/budgettracker/budget-list.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% load render_table from django_tables2 %}
{% block content %}

    <h1>Budget </h1>
 <form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="mt-2"></div>
      <div id="average_budget"></div>   
      <div class="row mt-3"></div> 
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>    
        {% render_table table %}

{% endblock %}

templates/budgettracker/budgettracker_delete.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container">
      <div class="row justify-content-center">
        <div class="col-8">
          <h1 class="mt-2">Delete a Record</h1>
  <form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="mt-2"></div>
    <p>You sure you want to delete your <strong>{{ budgettracker.category }} </strong> transaction with an <strong>amount of ${{budgettracker.budget_amount|floatformat:2}}</strong> dated on <strong>{{budgetracker.date}}</strong></p>
                <input class="btn btn-success" 
                       type="button" value="Keep the record - it is nice" 
                       onclick="window.history.go(-1);"/>
                <input class="btn btn-danger" type="submit" value="Destroy this record!"/>
            </form>  </form>
{% endblock %}

templates/budgettracker/budgettracker_form copy.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}



{% block content %}
<style>
.my-container{
  border: 5px solid red;
  }
</style>
<h1 class="text-center font-weight-lighter p-0 mt-2 ">Add a Budget</h1>

   <div class=" d-flex justify-content-center">
       <form method="post" class=" border p-2 bg-white font-weight-lighter">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="mt-2"></div>
    <div class="d-flex justify-content-center">
    <div id="average_budget" class="text-center my-container"> &nbsp;</div>
  </div>
    <div class="mt-2"></div>

    <button type="submit" class="btn btn-primary">Submit</button>

  </form>
  <div class="mt-3"></div>

</div>

 
{% block javascript %}
  	<script>
      var category = 0;
      var thedate = 0;
       $('#id_date').on('dp.change', function(e){ 
         thedate = $(this).val();
       });

  /*  $("#id_category").change(function()  {
     category = $(this).val();
       
      $.ajax({
        url: '/budgettracker/get_cat_budget/',
        data: {
          'category': category,
          'thedate': thedate
        },
        dataType: 'json',
        success: function (data) {
          console.log(data)
          if (data.data.budget_amount) {
            $("#last_month_budget").append("<p>Last month's budget was $"+data.data.budget_amount+"</p>")
          }
        }
      });

    });*/

     
      $('#id_category').change(function(){
       var category = $(this).find('option:selected').text();
       var date = $('#id_date').val();
       $.ajax({
         url: 'ajax/get_budget_average',
         data:{
           'category': category,
           'date': date
         },
         dataType:'json',
         success: function (data){
         var averagespend =  (data['category_average_spend']['monthly_spend__avg']);
         var averagebudget = (data['category_average_budget']['budget_amount__avg']);
         var budget_left = (data['budget_left']);
         console.log (budget_left);
         if (averagespend == null)
         {
           averagespend = 0
         }
         if (averagebudget == null)
         {
           averagebudget = 0
         }
         var avgspend = averagespend.toFixed(2);    
         var avgbudget = averagebudget.toFixed(2);   
         var bud_left = budget_left.toFixed(2);
         console.log (data) 
        //$('#average_budget').appendTo('<p class="text-primary"><strong><i>Budget left this month: $'+bud_left+'</i></strong></p>'+'<p>'+'Over the last 3 months you have spent $<strong>'+avgspend+ '</strong> on the '+ category + ' category. Your average budget over the last 3 months has been <strong>$' + avgbudget +'</strong>.</p>')
         $('#average_budget').append('<p class="text-primary"><strong><i>Budget left this month: $'+bud_left+'</i></strong></p>'+'<p>'+'Over the last 3 months you have spent $<strong>'+avgspend+ '</strong> on the '+ category + ' category. Your average budget over the last 3 months has been <strong>$' + avgbudget +'</strong>.</p>' )
       //$('<p class="text-primary"><strong><i>Budget left this month: $'+bud_left+'</i></strong></p>'+'<p>'+'Over the last 3 months you have spent $<strong>'+avgspend+ '</strong> on the '+ category + ' category. Your average budget over the last 3 months has been <strong>$' + avgbudget +'</strong>.</p>').appendTo('#average_budget')
      
         }
       });    
       });
  </script>

{% endblock %}
{% endblock %}

templates/budgettracker/budgettracker_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}



{% block content %}


<h1 class="text-center font-weight-lighter p-0 mt-2 ">Add a Budget</h1>
<p>When you add a budget, once you select a category, you will see what some of your historical spend is and how much you have to budget this month.  This will help you understand what you can budget this month.</p>

<div class="col-md-6 col-9  col-lg-5 col-xl-4 mx-lg-auto bg-white border p-3">
<form method="post" class="font-weight-lighter">
  {% csrf_token %}
    {% for form_field in form %} 
    <div class="row pl-3">
      {{ form_field|as_crispy_field }}
    </div>
    {% endfor %} 
    <div class="mt-2"></div> 
    <div class="row pl-3">

    <div id="average_budget"></div>
  </div>
  <div class="row pl-3">
    <button type="submit" class="btn btn-primary">Add Budget</button>
  </div>
  <div class="mb-2"></div> 

</form>
</div>
<div class="mb-3"></div>

{% block javascript %}
  	<script>
      var category = 0;
      var thedate = 0;
       $('#id_date').on('dp.change', function(e){ 
         thedate = $(this).val();
       });

  /*  $("#id_category").change(function()  {
     category = $(this).val();
       
      $.ajax({
        url: '/budgettracker/get_cat_budget/',
        data: {
          'category': category,
          'thedate': thedate
        },
        dataType: 'json',
        success: function (data) {
          console.log(data)
          if (data.data.budget_amount) {
            $("#last_month_budget").append("<p>Last month's budget was $"+data.data.budget_amount+"</p>")
          }
        }
      });

    });*/

     
      $('#id_category').change(function(){
        $("#average_budget").empty();
       var category = $(this).find('option:selected').text();
       var date = $('#id_date').val();
       $.ajax({
         url: 'ajax/get_budget_average',
         data:{
           'category': category,
           'date': date
         },
         dataType:'json',
         success: function (data){
         var averagespend =  (data['category_average_spend']['monthly_spend__avg']);
         var averagebudget = (data['category_average_budget']['budget_amount__avg']);
         var budget_left = (data['budget_left']);
         console.log (budget_left);
         if (averagespend == null)
         {
           averagespend = 0
         }
         if (averagebudget == null)
         {
           averagebudget = 0
         }
         var avgspend = averagespend.toFixed(2);    
         var avgbudget = averagebudget.toFixed(2);   
         var bud_left = budget_left.toFixed(2);
         console.log (data) 
        //$('#average_budget').appendTo('<p class="text-primary"><strong><i>Budget left this month: $'+bud_left+'</i></strong></p>'+'<p>'+'Over the last 3 months you have spent $<strong>'+avgspend+ '</strong> on the '+ category + ' category. Your average budget over the last 3 months has been <strong>$' + avgbudget +'</strong>.</p>')
         $('#average_budget').append('<p class="text-primary"><i>Budget left this month:<strong> $'+bud_left+'</i></strong></p>'+'<ul><li> Average 3 month budget for '+ category + ': <strong>$' + avgbudget +'</strong></li><li>Your average spend has been $<strong>'+avgspend+ '</strong></li></ul>' )
       //$('<p class="text-primary"><strong><i>Budget left this month: $'+bud_left+'</i></strong></p>'+'<p>'+'Over the last 3 months you have spent $<strong>'+avgspend+ '</strong> on the '+ category + ' category. Your average budget over the last 3 months has been <strong>$' + avgbudget +'</strong>.</p>').appendTo('#average_budget')
      
         }
       });    
       });
  </script>

{% endblock %}
{% endblock %}