mybudget/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('categories/', include('categories.urls')),    
    path('users/', include('users.urls')), 
    path('accounts/', include('accounts.urls')),
    path('accounthistory/', include('accounthistory.urls')),
    path ('transfers/', include('transfers.urls')),
    path ('transactions/', include('transactions.urls')),
    path ('budgettracker/', include('budgettracker.urls'))
]

transactions/urls.py
from django.urls import path
from transactions.views import TransactionCreate, TransactionDelete, TransactionUpdate, TransactionList

from . import views


urlpatterns = [
    path('', views.index, name='transaction-index'),
    path('', TransactionList.as_view(), name='transaction-index'),
#    path('add', views.transactioncreate , name='transactioncreate'),
    path('add', TransactionCreate.as_view(), name='transaction-add'),
    path('<int:pk>/update', TransactionUpdate.as_view(), name='transaction-update'),
    path('<int:pk>/delete', TransactionDelete.as_view(), name='transaction-delete'),
    path ('ajax/get_account', views.get_account, name='get_account'),
    path ('ajax/category_budget_check', views.category_budget_check, name='category_budget_check'),
    path ('category-details/<int:categoryid>/', views.category_details, name='category-details'),
]

users/urls.py
from django.urls import path
from . import views
from users.views import RegisterView, LoginView, PasswordResetView, PasswordChangeView, PasswordChangeDoneView, PasswordResetDoneView, PasswordResetCompleteView, PasswordResetConfirmView
from django.contrib.auth import views as auth_views
urlpatterns = [

    path('register/', RegisterView.as_view(), name='register'),
    path ('login/',LoginView.as_view(), name='login'),
    path ('logout/',auth_views.LogoutView.as_view(), name='logout'),
    path ('password-reset/',PasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('password-change/', PasswordChangeView.as_view(), name='password_change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(), name='password_change_done'),
 

]

transactions/models.py
from django.db import models
from django.forms import ModelForm
from categories.models import Category
from accounts.models import Account
from django.contrib.auth.models import User
class Transaction(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default = 1) 
    store = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    amount = models.FloatField()
    trans_date = models.DateField(verbose_name= ('Transaction Date'))
   #add a category as a foreign key later that pulls this in as a dropdown
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    account_name = models.ForeignKey(Account, on_delete=models.CASCADE)


    def get_absolute_url(self):
        return reverse('transactions-index', args=[self.id])
    
    def __str__(self):
        return '%s  %s  %s %s %s %s' %(self.store, self.description, self.amount, self.trans_date, self.category, self.account_name)

transactions/forms.py
from django import forms
from bootstrap_datepicker_plus import DatePickerInput, MonthPickerInput, DateTimePickerInput
from django.forms import ModelForm
import datetime
from accounts.models import Account
from categories.models import Category
from .models import Transaction

class CreateTransactionForm(forms.ModelForm):
    CHOICES = [('spend', 'Spend'), ('income', 'Income/Refund')]
    transaction_type = forms.ChoiceField(
        choices = CHOICES, # this is optional
        widget = forms.RadioSelect,
        initial ='spend'
    )
    class Meta:
        model = Transaction
        fields =('store','description','transaction_type','category','amount', 'account_name', 'trans_date')
        widgets = {
            'trans_date': DatePickerInput(format='%m/%d/%Y').start_of('transaction days'), # default date-format %m/%d/%Y will be used
        }
    def __init__(self, *args, logged_user_id=None, **kwargs):
       super().__init__(*args, **kwargs)
       if logged_user_id is not None:
           self.fields['category'].queryset = Category.objects.filter(user=logged_user_id)
           self.fields['account_name'].queryset = Account.objects.filter(user=logged_user_id)        
    def clean_amount(self):
       for field, value in self.cleaned_data.items():
            amount = self.cleaned_data['amount']

       if self.cleaned_data['transaction_type']=='spend':
               amount = amount *-1
 
       return amount
    
    def clean_trans_date(self):
        trans_date = self.cleaned_data['trans_date']
        return trans_date
        
    def clean_description(self):
        description =  self.cleaned_data ['description']
        return description

    def clean_store(self):
        store = self.cleaned_data['store']
        return store

    def clean_account_name(self):
        account_name = self.cleaned_data ['account_name']
        return (account_name)

    def clean_category(self):
        category = self.cleaned_data ['category']
        return (category)



class UpdateTransactionForm(forms.ModelForm):
    CHOICES = [('spend', 'Spend'), ('income', 'Income/Refund')]
    transaction_type = forms.ChoiceField(
        choices = CHOICES, # this is optional
        widget = forms.RadioSelect, required=True)
    class Meta:
        model = Transaction
        fields =('account_name','store','description','category','transaction_type','amount', 'trans_date')
        widgets = {
            'trans_date': DatePickerInput(), # default date-format %m/%d/%Y will be used
        }


    def __init__(self, *args, logged_user_id=None, **kwargs):
       super().__init__(*args, **kwargs)
       if logged_user_id is not None:
           self.fields['category'].queryset = Category.objects.filter(user=logged_user_id)
           self.fields['account_name'].queryset = Account.objects.filter(user=logged_user_id)    
       #    self.fields['amount'] = self.cleaned_data['amount']
       #    print (self.fields['amount']) = Transaction.objects.filter(user=logged_user_id)
           print ('-----stuff-----------')
           amount = self.instance.amount
           if (amount < 0 ):
               self.fields['transaction_type'].initial = 'spend'
           else:
               self.fields['transaction_type'].initial = 'income'    

    def clean_amount(self):

       for field, value in self.cleaned_data.items():
           if self.cleaned_data['transaction_type']=='spend':
               amount = self.cleaned_data['amount'] *-1
           else:
               amount = self.cleaned_data['amount']    
       return amount

    def clean_trans_date(self):
        trans_date = self.cleaned_data['trans_date']
        return trans_date
    
 
        
    def clean_description(self):
        description =  self.cleaned_data ['description']
        return description

    def clean_store(self):
        store = self.cleaned_data['store']
        return store

    def clean_account_name(self):
        account_name = self.cleaned_data ['account_name']
        return (account_name)

    def clean_category(self):
        category = self.cleaned_data ['category']
        return (category)
        

transactions/views.py
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.http import JsonResponse
from django.template import loader
from django.db.models import Sum
from .models import Transaction
from budgettracker.models import BudgetTracker
from categories.models import Category
from accounts.models import Account
from accounthistory.models import AccountHistory
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView
from .forms import CreateTransactionForm, UpdateTransactionForm
from django.shortcuts import render, redirect, reverse
from datetime import datetime, date, timedelta
from calendar import monthrange
import calendar
from mybudget.common import get_first_of_month, get_last_of_month, get_first_of_next_month
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from dateutil import tz
from django.utils import timezone
@login_required


def index(request):
    template = loader.get_template('transactions/index.html')
    today = datetime.today()
    enddate = get_last_of_month (today)
    startdate = get_first_of_month(today)
    show_transactions = Transaction.objects.filter(user=request.user).order_by('-trans_date')
    total = Transaction.objects.filter(trans_date__range=[startdate, enddate], user=request.user).aggregate(sum=Sum('amount'))['sum'] or 0.00
    total = "{:.2f}".format(total)

    context = {
        'show_transactions':show_transactions,
        'total': total,
    }
    return HttpResponse(template.render(context, request))

class TransactionCreate (LoginRequiredMixin, CreateView):

     template_name = 'transactions/transaction_form.html'
     form_class = CreateTransactionForm
     success_url = reverse_lazy('transaction-index') 
     model = Transaction
     def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update(logged_user_id=self.request.user.id)

        return kwargs

     def form_valid(self, form):
        now = datetime.today()
        now_string = now.strftime('%Y-%m-%d %H:%M:%S')
        store = form.cleaned_data ['store']
        category = form.cleaned_data ['category']
        acct_name = form.cleaned_data['account_name']
        amount = form.cleaned_data['amount']
        trans_date = form.cleaned_data['trans_date']
        trans_date_no_time_string = str(trans_date.year)+'-' + str(trans_date.month) + '-'+ str(trans_date.day)
        trans_date_no_time = trans_date
        form.instance.user = self.request.user   
        user_id = self.request.user.id
        self.object = form.save()
     #   bud_date = str(trans_date.year) +"-" +str(trans_date.month) + "-"+ "1"
        bud_date = get_first_of_month(trans_date)
        #create a category budget for a transaction if it does not exist
 #       if (str(category) != 'Income' and str(category) !='Initial Balance'):
 #           print ('--------inside not!!!!!!!!!--------')
 #           if not BudgetTracker.objects.filter(date=bud_date, user=self.request.user, category__category=category).exists():
 #               budget_does_not_exist = 'Create a budget for this category before adding a transaction'
 #               bud_amount = amount
 #               if amount < 0:
 #                   bud_amount = bud_amount *-1
 #               new_budget = BudgetTracker(category=category, budget_amount = bud_amount, monthly_spend = '0', date = bud_date, user=self.request.user)
 #               new_budget.save()
        # get the latest account balance based on the transaction date.  This should account for a present record and going into the past.

        #latest_account = AccountBalance.objects.filter(account__account_name=acct_name).values('account__account_name', 'balance', 'balance_date').latest('balance_date')
       # get all accounts that are gte transaction
       
       
        latest_account = AccountHistory.objects.filter(account__account_name = acct_name, balance_date__lte=trans_date, account__user=self.request.user).values('account__account_name', 'balance', 'ate').order_by("-date")[0]
        print (latest_account)
        print('--------latest acount----')

        latest_account_date = latest_account['date']
        print (trans_date_no_time)
        if latest_account_date == trans_date:
            #just update the existing balance if a balance exists for date the transaction is suppsoed to 
            new_balance = latest_account['balance'] + amount
            print ('latest account balance:')
            print (latest_account['balance'])
            print ('new balance:')
            print (new_balance)
            update_account = AccountHistory.objects.filter(account__account_name = acct_name, balance_date=trans_date, account__user=self.request.user).update(balance = new_balance)
            print ('update')
            print (update_account)
            records_to_update = AccountHistory.objects.filter(account__account_name=acct_name, account__user=self.request.user, balance_date__gt=trans_date)
            print ('records to update:')
            print (records_to_update)
        #update all potential future record balances
            for record in records_to_update:
                record.balance = record.balance + amount
                record.save() 
            # create a new record for account history
            print ('----new balance before account history add')
            print (new_balance)
            print (trans_date)
            print (latest_account['balance'])
      #      new_account_history_record = AccountHistory(user=self.request.user, account = acct_name, transaction=self.object, date=trans_date, balance = new_balance)
      #      new_account_history_record.save()
            new_acct_records_to_update = AccountHistory.objects.filter(account=acct_name, user=self.request.user, date__gt=trans_date, date__lte = now)
            print ('-----new acct records to update------')
            print (new_acct_records_to_update)
            for record in new_acct_records_to_update:
                print (record.balance)
                record.balance = record.balance + amount
                record.save()

        else:
            print ('-------IN ELSE?????')
        #create a new balance record if one doesn't exist for that date
            balance_description = str(store) +" "+ str(category)
            new_account_balance=amount + float(latest_account['balance'])   
            print('new account balance-----')
            print (new_account_balance)     
      #      new_record = AccountBalance(account=acct_name, balance_description = balance_description, balance=new_account_balance, balance_date=trans_date)
      #      new_record.save()
            new_account_history_record = AccountHistory(user=self.request.user, account = acct_name, transaction=self.object, date=trans_date, balance = new_account_balance)
            new_account_history_record.save() 
            new_acct_records_to_update = AccountHistory.objects.filter(account=acct_name, user=self.request.user, date__gt=trans_date, date__lte = now)
       #     records_to_update = AccountBalance.objects.filter(account__account_name=acct_name, account__user=self.request.user,balance_date__gt=trans_date, balance_date__lte = now.date())
            print ('----new account history reords to update ------')
            print (new_acct_records_to_update)
            print (records_to_update)
        #update any potential future records
        #    for record in records_to_update:
        #        record.balance = record.balance + amount
         #       record.save() 

            for record in new_acct_records_to_update:
                record.balance = record.balance + amount
                record.save()

        first_of_month = get_first_of_month(trans_date)

        next_first_of_month = get_first_of_next_month(trans_date)
 #get all transactions for this month, get the budget for the category, do the math on that category
        transaction_spend = Transaction.objects.filter(category__category = category, trans_date__range = [first_of_month, trans_date], user=self.request.user).aggregate(sum=Sum('amount'))['sum'] or 0.00
        print ('transaction spend so far--------------:')
        print (transaction_spend)

        category_budget = BudgetTracker.objects.filter(category__category = category, date__range = [first_of_month, trans_date], user=self.request.user)

        #category_spend = budget_amount - transaction_spend
        print ('cagegory_budget no user')
        print (category_budget)           
        for spend in category_budget:
             print ('inside loop------------')
             print (spend.monthly_spend)
             spend.monthly_spend = transaction_spend
             print (spend.monthly_spend)
             spend.save()
        
        check_category_carryover = Category.objects.filter(category=category, user=self.request.user).values('carry_over')
        print ('check_category_carryover-------')
        print (category)
        print (check_category_carryover)
        if check_category_carryover:
            category_budget_next = BudgetTracker.objects.filter(category__category = category, date = next_first_of_month, user=self.request.user)
            # if a budget doesn't exist for a category budget then create a new one
            if not category_budget_next:
                #get current month budget amount
                #
                print ('category_budget next month:')
                print (category_budget)

                for budget in category_budget:
                    budget_current_month = budget.budget_amount + amount
                    BudgetTracker.objects.create(category=budget.category, date = next_first_of_month, user=self.request.user, budget_amount=budget_current_month)

templates/transactions/category_transactions.html
{% extends 'base.html' %}
{% block content %}
<h1 class="text-center text-md-left font-weight-lighter p-0 mt-2">Transactions for <span class="text-info"> {{transactions.0.category}}</span> </h1>


<div class="mt-2"></div>
<table class="table table-light bg-white table-bordered">
<thead>
<tr>
<th scope="col">Store</th>
<th scope="col">Description</th>
<th scope="col">Amount</th>
<th scope="col">Account</th>
<th scope="col">Date</th>

</thead>
<tbody>
{% if transactions %}
    {% for transaction in transactions %}
        <tr>
        <td>{{ transaction.store }}</td>
        <td>{{ transaction.description }}</td>
        <td>${{ transaction.amount | floatformat:2 }}</td>
        <td>{{ transaction.account_name }}</td>
        <td>{{ transaction.trans_date }}</td>
       </tr>
    {% endfor %}
{% else %}
    Nothing available
{% endif %}
</tbody>
</table>

<p><strong>Total category spend or income this month: $</strong>{{ total|floatformat:2 }}

{% endblock %}

templates/transactions/index.html
{% extends 'base.html' %}
{% block content %}
   <h1 class="text-center text-md-left font-weight-lighter p-0 mt-2"> All Transactions</h1>
      <div class="d-flex">
         <div class="p-2"><a class = "btn btn-success" href="{%url "transaction-add"%}">Add a transaction</a></div>
      </div>
      <div class="mt-2"></div>

      <table class="table table-bordered bg-white">
         <thead>
             <tr>
                  <th scope="col">Store</th>
                  <th scope="col">Category</th>
                  <th scope="col">Category Name</th>
                  <th scope="col">Amount</th>
                  <th scope="col">Transaction Date</th>
                  <th scope="col">Account</th>
                  <th scope="col">Manage</th>
            </tr>      
         </thead>

         <tbody>
            {% if show_transactions %}
               {% for transaction in show_transactions %}
               <tr>
                 <td>{{ transaction.store }}</td>
                 <td> <a href="{%url "category-details" transaction.category_id%}">{{transaction.category}}</a></td>        
                 <td>{{ transaction.description }}</td>
                 <td>
                    {% if   transaction.amount > 0  %}
                        <div class="text-success">${{ transaction.amount | floatformat:2 }}</div>
                    {% else %}
                        <div class="text-danger"> ${{ transaction.amount|floatformat:2|cut:"-" }}   
                    {% endif %}   
                </td>
                <td>{{ transaction.trans_date }}</td>
                <td>{{ transaction.account_name }}</td>

                <td><a class = "btn btn-danger" href="{%url "transaction-delete" transaction.id%}">Delete</a> <a class = "btn btn-warning" href="{%url "transaction-update" transaction.id%}">Update</a></td>
             </tr>
            {% endfor %}
            {% else %}
          Nothing available
            {% endif %}
         </tbody>
      </table>

      {% endblock %}

templates/transactions/transaction_delete.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container">
      <div class="row justify-content-center">
        <div class="col-8">
          <h1 class="mt-2">Delete a Record</h1>
  <form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="mt-2"></div>
    <p>You sure you want to delete your <strong>{{ transaction.store }} </strong> transaction with an <strong>amount of ${{transaction.amount|floatformat:2}}</strong> dated on <strong>{{transaction.trans_date}}</strong></p>
                <input class="btn btn-success" 
                       type="button" value="Keep the record - it is nice" 
                       onclick="window.history.go(-1);"/>
                <input class="btn btn-danger" type="submit" value="Destroy this record!"/>
            </form>  </form>
{% endblock %}

templates/transactions/transaction_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<h1 class="text-center font-weight-lighter mt-2">Add or Update a Transaction</h1>
  <div id ="nobudget"></div>   
  <div class="col-sm-12">
  <div class=" row justify-content-center mb-3">
  <form method="post" class="text-left border p-3 bg-white font-weight-lighter">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="mt-2"></div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>
</div>
 {% block javascript %}
  	<script>
  $(document).ready(function(){

    the_value = $('#id_amount').val();
    if (the_value <0)
    {
      the_value=the_value*-1;
      $('#id_amount').val(the_value);
    }

  });
      $('#id_account_name').change(function(){
       var account = $(this).val();
       $.ajax({
         url: 'ajax/get_account',
         data:{
           'account': account
         },
         dataType:'json',
         success: function (data){
         $('#id_trans_date').data("DateTimePicker").minDate(data.date);

         }
       });    
       });
       $('#id_trans_date, #category').on('dp.change', function (event) {
      console.log ('change')
       var category = $('#id_category').find('option:selected').text();
       var date = $('#id_trans_date').val();
       console.log(date)
       $.ajax({
         url: 'ajax/category_budget_check',
         data:{
           'category': category,
           'date': date
         },
         dataType:'json',
         success: function (data){  

        //if you get no budgetracker value back send an error message
      //   var averagespend =  (data['category_average_spend']['monthly_spend__avg']);
      //   var averagebudget = (data['category_average_budget']['budget_amount__avg'])
      //   var avgspend = averagespend.toFixed(2);    
      //   var avgbudget = averagebudget.toFixed(2);   
         var budget_exist = (data['budget_exist']);
        console.log ('budget exists: '+ budget_exist)
         if (budget_exist == 'false'){

        $('#nobudget').append('<div class="alert alert-danger">' + 'There is no budget defined for this category.  Create one first!</div>');
        $("form").submit("disabled", true);

       //  $('#average_budget').text('Over the last 3 months you have spent $' + avgspend + ' on this category.' + ' Your avarage budget for this category is $' +avgbudget )
         }
         }
       });           
        });  
   
  </script>

{% endblock %} 
{% endblock %}

templates/transactions/transaction_update.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container">
      <div class="row justify-content-center">
        <div class="col-8">
          <h1 class="mt-2">Update this Transaction</h1>
  <div id ="nobudget"></div>        
  <form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="mt-2"></div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
 {% block javascript %}
  	<script>
  $(document).ready(function(){

    the_value = $('#id_amount').val();
    if (the_value <0)
    {
      the_value=the_value*-1;
      $('#id_amount').val(the_value);
    }

  });
      $('#id_account_name').change(function(){
       var account = $(this).val();
       $.ajax({
         url: 'ajax/get_account',
         data:{
           'account': account
         },
         dataType:'json',
         success: function (data){
         $('#id_trans_date').data("DateTimePicker").minDate(data.date);

         }
       });    
       });
       $('#id_trans_date, #category').on('dp.change', function (event) {
      console.log ('change')
       var category = $('#id_category').find('option:selected').text();
       var date = $('#id_trans_date').val();
       $.ajax({
         url: 'ajax/category_budget_check',
         data:{
           'category': category,
           'date': date
         },
         dataType:'json',
         success: function (data){  

        //if you get no budgetracker value back send an error message
      //   var averagespend =  (data['category_average_spend']['monthly_spend__avg']);
      //   var averagebudget = (data['category_average_budget']['budget_amount__avg'])
      //   var avgspend = averagespend.toFixed(2);    
      //   var avgbudget = averagebudget.toFixed(2);   
         var budget_exist = (data['budget_exist']);
        console.log ('budget exists: '+ budget_exist)
         if (budget_exist == 'false'){

        $('#nobudget').append('<div class="alert alert-danger">' + 'There is no budget defined for this category.  Create one first!</div>');
        $("form").submit("disabled", true);

       //  $('#average_budget').text('Over the last 3 months you have spent $' + avgspend + ' on this category.' + ' Your avarage budget for this category is $' +avgbudget )
         }
         }
       });           
        });  
   
  </script>

{% endblock %} 
{% endblock %}